# Set the server context path
server.servlet.context-path=/api/v1

# JPA & Hibernate settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url= ${RDB_URL :jdbc:postgresql://localhost:5432/transfi_db}
spring.datasource.username= ${RDB_USERNAME :prince}
spring.datasource.password= ${RDB_PASSWORD :amin}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Security Configuration
jwtSecret=${JWT_SECRET:9cfbafc7c809ec811c4443bfb60767d65e8ac34868e42435ae9803300753e305}
currencyApiKey= ${CURRENCY_API_KEY: cur_live_nyIhD672YgdGK1a5nVfUBvax4C85Yv74AKWV0WWQ}